apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-public
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.clusters.public.replicas }}
  image: rabbitmq:4.1.3-management
  resources:
    {{- toYaml .Values.clusters.public.resources | nindent 4 }}
  persistence:
    storage: {{ .Values.clusters.public.storage | quote }}
  service:
    type: ClusterIP
    {{- if .Values.clusters.public.serviceAnnotations }}
    annotations:
      {{- toYaml .Values.clusters.public.serviceAnnotations | nindent 6 }}
    {{- end }}
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark.relative = 0.7
      tcp_listen_options.backlog = 128
      tcp_listen_options.nodelay = true
      tcp_listen_options.linger.on = true
      tcp_listen_options.linger.timeout = 0
      tcp_listen_options.keepalive = false
    additionalPlugins:
      {{- toYaml .Values.clusters.public.additionalPlugins | nindent 6 }}
